name: Build Image from Dockerfile 
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build_image:
    name: Build ${{ matrix.prefix }} image for ${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
         - prefix: manylinux
           version: '2_28'
           arch: x86_64
           platforms: linux/amd64
           runs-on: ubuntu-latest
         - prefix: manylinux
           version: '2_28'
           arch: aarch64
           platforms: linux/arm64
           runs-on: ubuntu-24.04-arm
         - prefix: musllinux
           version: '1_2'
           arch: x86_64
           platforms: linux/amd64
           runs-on: ubuntu-latest
         - prefix: musllinux
           version: '1_2'
           arch: aarch64
           platforms: linux/arm64
           runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile_${{ matrix.prefix }}_${{ matrix.version }}_${{ matrix.arch }}
        platforms: ${{ matrix.platforms }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.prefix }}_${{ matrix.version }}_${{ matrix.arch }}-hdf5
